### ISSUE TITLE
Could you provide a pytorch code？

### ISSUE THREAD

**Issue by Johnson-yue** [WANG-Chaoyue/EvolutionaryGAN#1]
Hi，thanks your code， but I can not understand Theano code。 Would you like provide pytorch code？Thanks again！

**Comment by ghost** [comment]
Hi, 
I'm interested in your pytorch version and would like to contribute to it if possible. 
Thank you!

**Comment by WANG-Chaoyue** [comment]
A basic pytorch implementation is released. Meanwhile, we will work on improving it.
